services:
  - type: web
    name: pastesafe
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn server:app
    envVars:
      - key: PORTAL_PORT
        value: 5003
